version: '3.8'

services:
    customers_api:
        build:
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8080:8080"
    customers_client:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - "3000:3000"